version: '3'
services:
  atando:
    build:
      context: .
      args: 
        _host: 0.0.0.0
        _port: 3000
    links:
    - db
    container_name: atando-react
    ports:
    - 3000:3000
    volumes:
    - /home/david/atando-api:/app
    

  db:
    container_name: atando-mysql
    volumes:
    - /tmp/mysql:/var/lib/mysql
    image: mysql
    ports:
      - "33006:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_USER: node
      MYSQL_PASSWORD: 12345678
      MYSQL_DATABASE: user