version: '3'
services:
  atando-api:
    build:
      context: .
      args: 
        _host: 0.0.0.0
        _port: 3000
        _firebase_host: https://www.googleapis.com
        _api_key: _api_key
    links:
    - db
    container_name: atando-api
    ports:
    - 3000:3000
    volumes:
    - /home/david/atando-api:/app
    
  atando-app:
    build:
      context: ../atando-app/
    links:
    - db
    - atando-api
    container_name: atando-app
    ports:
    - 3001:3000
    volumes:
    - /home/david/atando-app:/app
    

  db:
    container_name: atando-mysql
    volumes:
    - /tmp/mysql:/var/lib/mysql
    image: mysql
    ports:
      - "33006:3306"
    environment:
      MYSQL_ROOT_PASSWORD: MYSQL_ROOT_PASSWORD
      MYSQL_USER: MYSQL_USER
      MYSQL_PASSWORD: MYSQL_PASSWORD
      MYSQL_DATABASE: MYSQL_DATABASE
